apiVersion: krew.googlecontainertools.github.com/v1alpha2
kind: Plugin
metadata:
  name: wider
spec:
  version: "{{ .TagName }}"
  platforms:
  - selector:
      matchExpressions:
      - {key: os, operator: In, values: [darwin, linux]}
    {{addURIAndSha "https://github.com/boriscosic/wider/releases/download/{{ .TagName }}/{{ .TagName }}.zip" .TagName }}
    files:
    - from: "*"
      to:  "."
    bin: "kubectl-wider"
  shortDescription: >-
    Get pod and associated node information with one command
  homepage: https://github.com/boriscosic/wider
  description: |
    Get pods and associated node information. Extend the output with custom-columns 
    by leveraging keys from pod or node specs. 
    Examples:
    `$ kubectl wider`
    `$ kubectl wider -n istio-system -o custom-columns="NAME:.metadata.name,NODE:.node.metadata.name` 